name: upload chrome web store

on:
  push:
    branches: [master,dev]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: install ng cli
        run: |
          sudo npm install -g @angular/cli

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Node 12.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '12.x'

      - name: npm install and ng build
        run: |
          npm install
          ng build --prod

      - name: cd dist
        run: |
          cd dist/afk-chrome-extension
          pwd

      - uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: awayfromkeyboard
          AWS_ACCESS_KEY_ID: AKIAXW6HU27E5SWAEVOL
          AWS_SECRET_ACCESS_KEY: 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
          AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'dist/afk-chrome-extension/'      # optional: defaults to entire repository

      - uses: actions/upload-artifact@v2
        with:
          name: afk
          path: /home/runner/work/project_AFK/project_AFK/dist/afk-chrome-extension/

      - name: Chrome Extension upload & publish
        if: github.ref == 'refs/heads/main'
        uses: Passiverecords/chrome-extension-upload-action@1.4.1
        with:
          refresh-token: '1//06uWcWWkVxYa0CgYIARAAGAYSNwF-L9IrzAp5WTOO53NmjQXDDEgYBDrYJ_SC1z1DHOHT1meoOOjj_gVr3YvfymU0GmTdWH0x5u0'
          client-id: '206079853979-uv3536u335r203ige4rsi3kl0jftkrn1.apps.googleusercontent.com'
          client-secret: 'oeMcFVqUqzJ_sOiwTVMjzJPd'
          file-name: './afk-chrome-extension/afk.zip'
          app-id: 'njeooeindgiaogbemmdcihembojhcdpg'

